name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: '*'
env:
  NODE_VERSION: 14
  ASSET_PREFIX: ${{ github.ref == 'refs/heads/main' && '/nextjs-styled-system' || '' }}
jobs:
  install:
    name: Install Node Dependencies
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip')}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        run: yarn
  lint:
    name: Lint
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Lint
        run: yarn lint
  test:
    name: Test
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Test
        run: yarn test
  typecheck:
    name: Typecheck
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Typecheck
        run: yarn typecheck
  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          name: nextjs-build
          path: ./out/
  deploy:
    name: Deploy to GH Pages
    needs: [lint, test, typecheck, build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Cache
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn
      - name: Make Artifact Directory
        run: mkdir out
      - uses: actions/download-artifact@v2
        with:
          name: nextjs-build
          path: ./out
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
